%Extract the parameters from 2 output files generated by ClusterAlign and
%order the dual reconstruction based on the two aligned serieses using function reconstruct_dual 
[filename,path1] = uigetfile('D:\results\*.output.txt','Fetch ClusterAlign-output file from first aligned tilt series');
Chosen_Filename_output=[path1 filename];
fileID = fopen(Chosen_Filename_output,'r');
for n=1:20
    a=fgetl(fileID);
    if length(a)>33
        if strcmp(a(1:30),'clusteralign_astra_reconstruct')
            sline=a(31:length(a));
            break;
        end
    end
end
sline=strrep(sline,'(','');
sline=strrep(sline,')','');
sline=strrep(sline, char(39),'');
formatSpec = '%d,%f,%f,%s';
param1 = textscan(sline,formatSpec);
fclose(fileID);
cosine=param1{1};
phi_deg1=param1{2};
psi_deg1=param1{3};
subline=string(param1(4));
subline=strrep(subline, char(39),'');
subpar=strsplit(subline,',');
alifile1=char(subpar{1});
disp(sprintf('File a: %s', alifile1));
anglefile1=char(subpar{2});

[filename,path1] = uigetfile('D:\results\*.output.txt','Fetch ClusterAlign-output file from second aligned tilt series');
Chosen_Filename_output=[path1 filename];
fileID = fopen(Chosen_Filename_output,'r');
for n=1:20
    a=fgetl(fileID);
    if length(a)>33
        if strcmp(a(1:30),'clusteralign_astra_reconstruct')
            sline=a(31:length(a));
            break;
        end
    end
end
sline=strrep(sline,'(','');
sline=strrep(sline,')','');
sline=strrep(sline, char(39),'');
formatSpec = '%d,%f,%f,%s';
param2 = textscan(sline,formatSpec);
fclose(fileID);
phi_deg2=param2{2};
psi_deg2=param2{3};
subline=string(param2(4));
subline=strrep(subline, char(39),'');
subpar=strsplit(subline,',');
alifile2=char(subpar{1});
disp(sprintf('File b: %s', alifile2));
anglefile2=char(subpar{2});

reconstruct_dual(cosine,phi_deg1,psi_deg1,alifile1,anglefile1,phi_deg2,psi_deg2,alifile2,anglefile2);
disp('Findished dual reconsruction')

